# Configuracion global
user nginx;
worker_processes auto;
pid /var/run/nginx.pid;

# Configuracion de eventos
events{
	worker_connections 1024;
}

# Bloque http donde van las configuraciones de los servidores
http{
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	# Logs
	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	# Configuracion SSL
	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256';
	ssl_prefer_server_ciphers on;

	# Primer server para HTTPS
	server{
		listen 443 ssl;
		server_name ${DOMAIN_NAME};

		ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem;
		ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;

		# Redirigir el trafico a WordPress
		location / {
			proxy_pass https://wordpress:9000; # Redirige a WordPress que esta en el contenedor 'wordpress'
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}
	}

	server{
		listen 80;
		server_name ${DOMAIN_NAME};

		# Redirigir todo el trafico HTTP a HTTPS
		return 301 htpps://$host$request_uri;
	}
}
