db_name=${MYSQL_DATABASE}
db_user=${MYSQL_USER}
db_pwd=${MYSQL_PASSWORD}
root_pwd=${MYSQL_ROOT_PASSWORD}

CREATE DATABASE IF NOT EXISTS $db_name;

CREATE USER IF NOT EXISTS '$db_user'@'%' IDENTIFIED BY '$db_pwd';
GRANT ALL PRIVILEGES ON '$db_name'.* TO '$db_user'@'%';

CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '$root_pwd';
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root_pwd';
ALTER USER 'root'@'%' IDENTIFIED BY '$root_pwd';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
